# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPicture = QtWidgets.QMenu(self.menubar)
        self.menuPicture.setObjectName("menuPicture")
        self.menuFiltration = QtWidgets.QMenu(self.menubar)
        self.menuFiltration.setObjectName("menuFiltration")
        self.menuContours = QtWidgets.QMenu(self.menubar)
        self.menuContours.setObjectName("menuContours")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionResize = QtWidgets.QAction(MainWindow)
        self.actionResize.setObjectName("actionResize")
        self.actionRotate = QtWidgets.QAction(MainWindow)
        self.actionRotate.setObjectName("actionRotate")
        self.actionCrop = QtWidgets.QAction(MainWindow)
        self.actionCrop.setObjectName("actionCrop")
        self.actionROI = QtWidgets.QAction(MainWindow)
        self.actionROI.setObjectName("actionROI")
        self.actionHomogeneous = QtWidgets.QAction(MainWindow)
        self.actionHomogeneous.setObjectName("actionHomogeneous")
        self.actionMedian = QtWidgets.QAction(MainWindow)
        self.actionMedian.setObjectName("actionMedian")
        self.actionBilateral = QtWidgets.QAction(MainWindow)
        self.actionBilateral.setObjectName("actionBilateral")
        self.actionSobel_operator = QtWidgets.QAction(MainWindow)
        self.actionSobel_operator.setObjectName("actionSobel_operator")
        self.actionKenny_Detector = QtWidgets.QAction(MainWindow)
        self.actionKenny_Detector.setObjectName("actionKenny_Detector")
        self.actionHough_converting_to_search_for_lines = QtWidgets.QAction(MainWindow)
        self.actionHough_converting_to_search_for_lines.setObjectName("actionHough_converting_to_search_for_lines")
        self.actionObject_Detection = QtWidgets.QAction(MainWindow)
        self.actionObject_Detection.setObjectName("actionObject_Detection")
        self.actionComparison_of_contours_through_total_characteristics = QtWidgets.QAction(MainWindow)
        self.actionComparison_of_contours_through_total_characteristics.setObjectName("actionComparison_of_contours_through_total_characteristics")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuPicture.addAction(self.actionResize)
        self.menuPicture.addAction(self.actionRotate)
        self.menuPicture.addAction(self.actionCrop)
        self.menuPicture.addAction(self.actionROI)
        self.menuFiltration.addAction(self.actionHomogeneous)
        self.menuFiltration.addAction(self.actionMedian)
        self.menuFiltration.addAction(self.actionBilateral)
        self.menuFiltration.addAction(self.actionSobel_operator)
        self.menuContours.addAction(self.actionKenny_Detector)
        self.menuContours.addAction(self.actionHough_converting_to_search_for_lines)
        self.menuContours.addAction(self.actionObject_Detection)
        self.menuContours.addAction(self.actionComparison_of_contours_through_total_characteristics)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPicture.menuAction())
        self.menubar.addAction(self.menuFiltration.menuAction())
        self.menubar.addAction(self.menuContours.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Graphics editor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPicture.setTitle(_translate("MainWindow", "Picture"))
        self.menuFiltration.setTitle(_translate("MainWindow", "Filtration"))
        self.menuContours.setTitle(_translate("MainWindow", "Contours"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionResize.setText(_translate("MainWindow", "Resize"))
        self.actionRotate.setText(_translate("MainWindow", "Rotate"))
        self.actionCrop.setText(_translate("MainWindow", "Crop"))
        self.actionROI.setText(_translate("MainWindow", "ROI"))
        self.actionHomogeneous.setText(_translate("MainWindow", "Homogeneous"))
        self.actionMedian.setText(_translate("MainWindow", "Median"))
        self.actionBilateral.setText(_translate("MainWindow", "Bilateral"))
        self.actionSobel_operator.setText(_translate("MainWindow", "Sobel operator"))
        self.actionKenny_Detector.setText(_translate("MainWindow", "Kenny Detector"))
        self.actionHough_converting_to_search_for_lines.setText(_translate("MainWindow", "Hough converting to search for lines"))
        self.actionObject_Detection.setText(_translate("MainWindow", "Object Detection"))
        self.actionComparison_of_contours_through_total_characteristics.setText(_translate("MainWindow", "Comparison of contours through total characteristics"))

