# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbRadioButtons = QtWidgets.QGroupBox(self.centralwidget)
        self.gbRadioButtons.setObjectName("gbRadioButtons")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbRadioButtons)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rbUTF = QtWidgets.QRadioButton(self.gbRadioButtons)
        self.rbUTF.setObjectName("rbUTF")
        self.verticalLayout_2.addWidget(self.rbUTF)
        self.rbCp = QtWidgets.QRadioButton(self.gbRadioButtons)
        self.rbCp.setObjectName("rbCp")
        self.verticalLayout_2.addWidget(self.rbCp)
        self.verticalLayout.addWidget(self.gbRadioButtons)
        self.gbCheckBoxes = QtWidgets.QGroupBox(self.centralwidget)
        self.gbCheckBoxes.setObjectName("gbCheckBoxes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbCheckBoxes)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cbBold = QtWidgets.QCheckBox(self.gbCheckBoxes)
        self.cbBold.setObjectName("cbBold")
        self.verticalLayout_3.addWidget(self.cbBold)
        self.cbItalic = QtWidgets.QCheckBox(self.gbCheckBoxes)
        self.cbItalic.setObjectName("cbItalic")
        self.verticalLayout_3.addWidget(self.cbItalic)
        self.cbUnderlined = QtWidgets.QCheckBox(self.gbCheckBoxes)
        self.cbUnderlined.setObjectName("cbUnderlined")
        self.verticalLayout_3.addWidget(self.cbUnderlined)
        self.verticalLayout.addWidget(self.gbCheckBoxes)
        self.gbComboBox = QtWidgets.QGroupBox(self.centralwidget)
        self.gbComboBox.setObjectName("gbComboBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbComboBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.gbComboBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.gbComboBox)
        self.pbReset = QtWidgets.QPushButton(self.centralwidget)
        self.pbReset.setObjectName("pbReset")
        self.verticalLayout.addWidget(self.pbReset)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbRadioButtons.setTitle(_translate("MainWindow", "Encoding"))
        self.rbUTF.setText(_translate("MainWindow", "UTF-8"))
        self.rbCp.setText(_translate("MainWindow", "cp1251"))
        self.gbCheckBoxes.setTitle(_translate("MainWindow", "Font style"))
        self.cbBold.setText(_translate("MainWindow", "Bold"))
        self.cbItalic.setText(_translate("MainWindow", "Italic"))
        self.cbUnderlined.setText(_translate("MainWindow", "Underlined"))
        self.gbComboBox.setTitle(_translate("MainWindow", "Colour"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Black"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Green"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Red"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Yellow"))
        self.pbReset.setText(_translate("MainWindow", "Reset"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


